//roles
export const RECEIVE_ROLES = 'RECEIVE_ROLES';

//categories
export const LOADING_CATEGORY = 'LOADING_CATEGORY';
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const DELETED_CATEGORY = "DELETED_CATEGORY";

//subcategories
export const LOADING_SUBCATEGORY = 'LOADING_SUBCATEGORY';
export const RECEIVE_SUBCATEGORY = 'RECEIVE_SUBCATEGORY';
export const RECEIVE_SUBCATEGORIES_BY_CAT = 'RECEIVE_SUBCATEGORIES_BY_CAT';
export const DELETED_SUBCATEGORY = "DELETED_SUBCATEGORY";

//quizzes
export const LOADING_QUIZ = 'LOADING_QUIZ';
export const RECEIVE_QUIZ = 'RECEIVE_QUIZ';
export const RECEIVE_QUIZ_BY_CAT = 'RECEIVE_QUIZ_BY_CAT';
export const DELETED_QUIZ_BY_CAT = 'DELETED_QUIZ_BY_CAT';
export const EDIT_QUIZ = 'EDIT_QUIZ';
export const DELETED_QUIZ = "DELETED_QUIZ";
export const CLEAR_QUIZZES = "CLEAR_QUIZZES";

//questions
export const LOADING_QUESTION = 'LOADING_QUESTION';
export const RECEIVE_QUESTION = 'RECEIVE_QUESTION';
export const RECEIVE_QUESTIONS_BY_QUIZ = 'RECEIVE_QUESTIONS_BY_QUIZ';
export const EDIT_QUESTION = 'EDIT_QUESTION';
export const DELETED_QUESTION = "DELETED_QUESTION";
export const CLEAR_QUESTIONS = "CLEAR_QUESTIONS";

//questiontypes
export const LOADING_QUESTIONTYPE = 'LOADING_QUESTIONTYPE';
export const RECEIVE_QUESTIONTYPE = 'RECEIVE_QUESTIONTYPE';
export const EDIT_QUESTIONTYPE = 'EDIT_QUESTIONTYPE';
export const DELETED_QUESTIONTYPE = "DELETED_QUESTIONTYPE";

//modal
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

//Sign Up User
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
export const RESET_USER = 'RESET_USER';

//Sign In User
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_FAILURE = 'SIGNIN_USER_FAILURE';

//log out user
export const LOGOUT_USER = 'LOGOUT_USER';

//Form create questiontypes
export const LOAD_OPTIONS = 'LOAD_OPTIONS';